---
#
# docker-compose.yml: This wiki contains a Docker Compose configuration tailored for Synology NAS environments.
#
# Tools Included:
#   - Material for MkDocs: Generates static documentation from Markdown files with Material theme.
#
# For more information about Material for MkDocs, visit: https://squidfunk.github.io/mkdocs-material/
#

#
# Docker Compose version on the target system
#
version: "2.9"

#
# Define the services section
#
services:
  #
  # Define the 'mkdocs-material' service
  #
  mkdocs-material:
    # Docker image build and container information
    image: ${MKDOCS_IMAGE}:${MKDOCS_TAG}              # Set build image name and tag
    build:                                            # Build to install additional plugins
      context: docker                                 # Docker build context
      dockerfile: Dockerfile                          # Dockerfile to use for the build
      args:                                           # Build arguments passed to Dockerfile
        MKDOCS_TAG: ${MKDOCS_TAG}                     # Specify FROM base image tag as a build argument
    container_name: mkdocs-material-${MKDOCS_TAG}     # Append Docker image tag to container name
    restart: unless-stopped                           # Restart the container unless explicitly stopped
    network_mode: bridge                              # Use the default bridge network
    hostname: mkdocs-material                         # Set the container hostname
    labels:                                           # Add container labels
      - "com.centurylinklabs.watchtower.enable=false" # Exclude from Watchtower as this image is local

    # Define resource limits
    mem_limit: ${MKDOCS_MEM_LIMIT}
    cpu_shares: ${MKDOCS_CPU_SHARES}

    # Enable interactive terminal for the container
    stdin_open: true
    tty: true

    # Define the host and container ports
    ports:
      - ${MKDOCS_PORT}:8000

    # Define the container environment
    environment:
      - MKDOCS_GH_TOKEN=${MKDOCS_GH_TOKEN} # GitHub access token for API calls

    # Mount host directories into the container
    volumes:
      - ${HOST_WIKI_PATH}:/docs:rw # Mount docs directory
