---
site_name: Celestial Codex
site_description: "Celestial Codex: where wisdom shines like stars"
site_url: https://pages.github.com/
repo_url: https://github.com/scottgigawatt/wiki
repo_name: scottgigawatt/wiki
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 Scott Gigawatt

theme:
  name: material
  logo_dark_mode: assets/images/logos/logo-black-hole-dark.svg
  logo_light_mode: assets/images/logos/logo-black-hole-dark.svg
  favicon: assets/images/logos/favicon.svg
  icon:
    repo: fontawesome/brands/git-alt
    # edit: material/pencil
    # view: material/eye
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - toc.follow
    # - toc.integrate
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - header.autohide
  custom_dir: material

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/tablesort.js

plugins:
  - search
  - git-revision-date:
      modify_md: false
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: timeago
      fallback_to_build_date: true
      enable_creation_date: true
  - git-committers:
      repository: scottgigawatt/wiki
      branch: main
      enabled: !ENV [CI, true]
      token: !ENV ["MKDOCS_GH_TOKEN"]

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - tables
  - toc:
      permalink: true
      separator: "-"
  - footnotes
  - pymdownx.magiclink
  - attr_list
  - md_in_html
  - meta
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/assets/icons
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scottgigawatt/wiki
      name: 🌟✨ Celestial Codex 📚✨
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repositories/scottgigawatt
      name: ⚡️ Scott Gigawatt
    - icon: fontawesome/brands/discord
      link: https://discord.gg/b8kyRaFZJr
      name: ✨ASTERES✨

nav:
  - Home:
      - index.md
      - Using MkDocs:
          - mkdocs/index.md
          - FAQ: mkdocs/mkdocs-faq.md
  - Reference:
      - reference/index.md
      - Synology:
          - Direct Ethernet Config: reference/synology/direct-ethernet-config.md
  - GitHub:
      - github/index.md
      - Projects: github/projects.md
  - Hosting:
      - Hosting and Pool Maintenance: hosting/hosting_and_pool_maintenance.md
